Algoritmo "semnome"

Var

  escala : caractere
  temperatura : real

Inicio

      escreva("Você vai digitar a temperatura em qual escala (C/F)?: ")
      leia(escala)

      se escala = "F" entao
         escreva("Digite a temperatura em Fahrenheit: ")
         leia(temperatura)
         senao
              se escala = "C" entao
                 escreva("Digite a temperatura em Celsius: ")
                 leia(temperatura)
      fimse
           fimse
           
      

Fimalgoritmo
